name: Tests
on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
jobs: 
    run_unit_tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: |
                cd tests/unit
                python test_my_utils.py
    run_func_tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: |
                cd tests/func
                bash test_print_fires.sh
    run_style_check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: pycodestyle $(git ls-files "*.py")